// constants/images.ts - COMPLETE VERSION with all images properly implemented

export const COMPANY_INFO = {
  name: 'Goodwill Diagnostics Ltd',
  shortName: 'Goodwill',
  registrationNumber: '80034316306305',
  phone1: '+256775385903',
  phone2: '+256703494876',
  phone: '+256775385903 | +256703494876',
  email: 'goodwilldiagnosticltd60@gmail.com',
  location: 'Sure House | Plot No. 1 Bombo Road',
  address: 'Sure House, Plot No. 1 Bombo Road, Kampala, Uganda',
  fullAddress: 'Sure House, Plot No. 1 Bombo Road, Kampala, Uganda',
  mapUrl: 'https://maps.google.com/?q=Sure+House+Plot+1+Bombo+Road+Kampala',
};

export const MEDICAL_IMAGES = {
  // ============ LOGO ============
  logo: {
    main: '/images/logo/good.png',
    favicon: '/images/logo/good.png',
  },

  // ============ HERO & BANNERS ============
  hero: {
    main: '/images/hero/doctor-patient.jpg',
    hospital: '/images/hero/hospital.jpg',
    doctorPatient: '/images/hero/doctor-patient.jpg',
  },

  // ============ CATEGORY BANNERS ============
  categories: {
    mobility: '/images/categories/mobility.jpg',
    respiratory: '/images/categories/respiratory.jpg',
    hospitalFurniture: '/images/categories/hospital-furniture.jpg',
    diagnostic: '/images/categories/diagnostic.jpg',
    ppe: '/images/categories/ppe.jpg',
    homeCare: '/images/categories/home-care.jpg',
  },

  // ============ PRODUCT IMAGES ============
  products: {
    wheelchair: '/images/products/wheelchair.jpg',
    wheelchairElectric: '/images/products/wheelchair2.jpg',
    oxygen: '/images/products/oxygen.jpg',
    cpap: '/images/products/oxygen.jpg',
    hospitalBed: '/images/products/hospital-bed.jpg',
    examTable: '/images/products/medical-bed7.jpg',
    bpMonitor: '/images/products/bp-monitor.jpg',
    stethoscope: '/images/products/stethoscope.jpg',
    thermometer: '/images/products/thermometer.jpg',
    n95Mask: '/images/products/ppe-mask.jpg',
    gloves: '/images/products/gloves.jpg',
    patientMonitor: '/images/products/patient-monitor.jpg',
  },

  // ============ ABOUT PAGE IMAGES ============
  about: {
    team: '/images/about/team.jpg',
    facility: '/images/about/facility.jpg',
    ceo: '/images/about/ceo.jpg',
  },

  // ============ CONTACT PAGE IMAGES ============
  contact: {
    office: '/images/contact/office.jpg',
  },

  // ============ TESTIMONIALS ============
  testimonials: {
    doctor1: '/images/testimonials/doctor1.jpg',
    doctor2: '/images/testimonials/doctor2.jpg',
    patient1: '/images/testimonials/patient1.jpg',
    patient2: '/images/testimonials/patient2.jpg',
  },

  // ============ CLIENT LOGOS ============
  clients: {
    platinum: '/images/logo/platinum.jpg',
    ihk: '/images/logo/ink.jpeg',
    kampala: '/images/logo/kampala.jpg',
    mawano: '/images/logo/mawano.jpg',
    alshafa: '/images/logo/al-shaf.jpg',
    idi: '/images/logo/idi.jpg',
    doctors: '/images/logo/doctors.jpg',
    care: '/images/logo/care.jpg',
    cancer: '/images/logo/cancer.jpg',
    ruby: '/images/logo/ruby.jpg',
    shine: '/images/logo/shine.jpg',
    catherine: '/images/logo/catherine.jpg',
    nile: '/images/logo/nile.jpg',
    najjerra: '/images/logo/mengo.jpg',
  },
};

// ============ PRODUCTS DATABASE ============
export const PRODUCTS = [
  {
    id: 1,
    name: 'Premium Lightweight Wheelchair',
    slug: 'premium-lightweight-wheelchair',
    sku: 'MW-1001',
    price: 299.99,
    salePrice: 249.99,
    image: MEDICAL_IMAGES.products.wheelchair,
    category: 'Mobility Aids',
    categorySlug: 'mobility-aids',
    brand: 'Goodwill Diagnostics',
    rating: 4.8,
    reviewCount: 124,
    inventory: 15,
    description: 'Lightweight aluminum frame wheelchair with comfortable padded seat and removable armrests. Ideal for daily use.',
    features: ['Weight capacity: 300 lbs', 'Foldable design for easy transport', 'Padded armrests', '12" rear wheels'],
    deliveryEstimate: '2-3 business days',
    warranty: '2 years',
  },
  {
    id: 2,
    name: 'Electric Power Wheelchair',
    slug: 'electric-power-wheelchair',
    sku: 'MW-1002',
    price: 1299.99,
    salePrice: 1099.99,
    image: MEDICAL_IMAGES.products.wheelchairElectric,
    category: 'Mobility Aids',
    categorySlug: 'mobility-aids',
    brand: 'Goodwill Diagnostics',
    rating: 4.7,
    reviewCount: 56,
    inventory: 8,
    description: 'Electric wheelchair with joystick control and long battery life. Perfect for indoor and outdoor use.',
    features: ['Battery range: 15 miles', 'Weight capacity: 350 lbs', 'Joystick controller', 'Padded seat'],
    deliveryEstimate: '5-7 business days',
    warranty: '3 years',
  },
  {
    id: 3,
    name: 'Portable Oxygen Concentrator',
    slug: 'portable-oxygen-concentrator',
    sku: 'RE-2001',
    price: 899.99,
    salePrice: 799.99,
    image: MEDICAL_IMAGES.products.oxygen,
    category: 'Respiratory Equipment',
    categorySlug: 'respiratory',
    brand: 'HealthCare Pro',
    rating: 4.9,
    reviewCount: 89,
    inventory: 12,
    description: 'Compact and lightweight oxygen concentrator. Battery lasts up to 5 hours. FAA approved for travel.',
    features: ['Battery life: 5 hours', 'Weight: 5 lbs', 'Pulse dose delivery', 'FAA approved'],
    deliveryEstimate: '2-3 business days',
    warranty: '2 years',
  },
  {
    id: 4,
    name: 'CPAP Machine',
    slug: 'cpap-machine',
    sku: 'RE-2002',
    price: 599.99,
    salePrice: 549.99,
    image: MEDICAL_IMAGES.products.cpap,
    category: 'Respiratory Equipment',
    categorySlug: 'respiratory',
    brand: 'MedTech',
    rating: 4.8,
    reviewCount: 142,
    inventory: 18,
    description: 'Auto-adjusting CPAP with heated humidifier for sleep apnea therapy. Quiet operation.',
    features: ['Pressure range: 4-20 cmH2O', 'Auto-ramp', 'Heated humidifier', 'Quiet operation'],
    deliveryEstimate: '2-3 business days',
    warranty: '2 years',
  },
  {
    id: 5,
    name: 'Adjustable Hospital Bed',
    slug: 'adjustable-hospital-bed',
    sku: 'HF-3001',
    price: 1299.99,
    image: MEDICAL_IMAGES.products.hospitalBed,
    category: 'Hospital Furniture',
    categorySlug: 'hospital-furniture',
    brand: 'CarePlus',
    rating: 4.7,
    reviewCount: 56,
    inventory: 7,
    description: 'Fully adjustable electric bed with remote control and side rails for patient safety.',
    features: ['Weight capacity: 450 lbs', 'Includes side rails', 'Remote control', 'Easy-clean surface'],
    deliveryEstimate: '7-10 business days',
    warranty: '5 years',
  },
  {
    id: 6,
    name: 'Digital Blood Pressure Monitor',
    slug: 'digital-bp-monitor',
    sku: 'DD-4001',
    price: 49.99,
    image: MEDICAL_IMAGES.products.bpMonitor,
    category: 'Diagnostic Devices',
    categorySlug: 'diagnostic',
    brand: 'Vital Signs',
    rating: 4.8,
    reviewCount: 203,
    inventory: 45,
    description: 'Automatic inflation blood pressure monitor with large LCD display. Detects irregular heartbeat.',
    features: ['Large LCD display', '200 memory recall', 'Irregular heartbeat detection', 'Includes carrying case'],
    deliveryEstimate: '1-2 business days',
    warranty: '1 year',
  },
  {
    id: 7,
    name: 'Professional Stethoscope',
    slug: 'professional-stethoscope',
    sku: 'DD-4002',
    price: 89.99,
    salePrice: 79.99,
    image: MEDICAL_IMAGES.products.stethoscope,
    category: 'Diagnostic Devices',
    categorySlug: 'diagnostic',
    brand: 'MedTech',
    rating: 4.9,
    reviewCount: 178,
    inventory: 32,
    description: 'Dual-head stethoscope with non-chill rim and adjustable frequency. Ideal for medical professionals.',
    features: ['Non-chill rim', 'Adjustable frequency', 'Dual-head chestpiece', 'Stainless steel construction'],
    deliveryEstimate: '1-2 business days',
    warranty: '2 years',
  },
  {
    id: 8,
    name: 'N95 Respirator Masks (50 pack)',
    slug: 'n95-masks-50-pack',
    sku: 'PPE-5001',
    price: 89.99,
    image: MEDICAL_IMAGES.products.n95Mask,
    category: 'PPE & Disposables',
    categorySlug: 'ppe',
    brand: 'HealthCare Pro',
    rating: 4.7,
    reviewCount: 167,
    inventory: 0,
    description: 'FDA-approved N95 respirator masks. 95% filtration efficiency. Individually wrapped.',
    features: ['95% filtration efficiency', 'Adjustable nose clip', 'Latex-free straps', 'Individually wrapped'],
    deliveryEstimate: '3-5 business days',
    warranty: 'Non-returnable',
  },
  {
    id: 9,
    name: 'Nitrile Exam Gloves (100 pack)',
    slug: 'nitrile-gloves-100-pack',
    sku: 'PPE-5002',
    price: 24.99,
    image: MEDICAL_IMAGES.products.gloves,
    category: 'PPE & Disposables',
    categorySlug: 'ppe',
    brand: 'Goodwill Diagnostics',
    rating: 4.6,
    reviewCount: 98,
    inventory: 150,
    description: 'Powder-free nitrile exam gloves. Latex-free, puncture resistant. Available in sizes S/M/L.',
    features: ['Powder-free', 'Latex-free', 'Puncture resistant', 'Beaded cuff'],
    deliveryEstimate: '1-2 business days',
    warranty: '30-day return',
  },
  {
    id: 10,
    name: 'Digital Thermometer',
    slug: 'digital-thermometer',
    sku: 'DD-4003',
    price: 19.99,
    image: MEDICAL_IMAGES.products.thermometer,
    category: 'Diagnostic Devices',
    categorySlug: 'diagnostic',
    brand: 'Vital Signs',
    rating: 4.8,
    reviewCount: 312,
    inventory: 200,
    description: 'Fast and accurate digital thermometer with flexible tip. Memory recall and fever alert.',
    features: ['Fast reading: 10 seconds', 'Flexible tip', 'Memory recall', 'Fever alert'],
    deliveryEstimate: '1-2 business days',
    warranty: '1 year',
  },
  {
    id: 11,
    name: 'Patient Monitor',
    slug: 'patient-monitor',
    sku: 'HC-6001',
    price: 2499.99,
    image: MEDICAL_IMAGES.products.patientMonitor,
    category: 'Home Care Supplies',
    categorySlug: 'home-care',
    brand: 'Vital Signs',
    rating: 4.9,
    reviewCount: 34,
    inventory: 5,
    description: 'Monitors ECG, SpO2, blood pressure, and temperature. Ideal for hospital and home care.',
    features: ['ECG monitoring', 'SpO2 monitoring', 'Blood pressure', 'Temperature', '12" touch screen'],
    deliveryEstimate: '3-5 business days',
    warranty: '3 years',
  },
  {
    id: 12,
    name: 'Medical Exam Table',
    slug: 'medical-exam-table',
    sku: 'HF-3002',
    price: 899.99,
    image: MEDICAL_IMAGES.products.examTable,
    category: 'Hospital Furniture',
    categorySlug: 'hospital-furniture',
    brand: 'CarePlus',
    rating: 4.7,
    reviewCount: 42,
    inventory: 6,
    description: 'Electric medical exam table with adjustable height and positioning. Paper roll holder included.',
    features: ['Electric height adjustment', 'Backrest adjustment', 'Paper roll holder', 'Weight capacity: 500 lbs'],
    deliveryEstimate: '5-7 business days',
    warranty: '3 years',
  },
];

// ============ CATEGORIES WITH PRODUCT COUNTS ============
export const CATEGORIES = [
  {
    id: 1,
    name: 'Mobility Aids',
    slug: 'mobility-aids',
    image: MEDICAL_IMAGES.categories.mobility,
    description: 'Wheelchairs, walkers, and mobility scooters',
    icon: '🦽',
    productCount: PRODUCTS.filter(p => p.categorySlug === 'mobility-aids').length,
  },
  {
    id: 2,
    name: 'Respiratory',
    slug: 'respiratory',
    image: MEDICAL_IMAGES.categories.respiratory,
    description: 'Oxygen concentrators, CPAP, ventilators',
    icon: '💨',
    productCount: PRODUCTS.filter(p => p.categorySlug === 'respiratory').length,
  },
  {
    id: 3,
    name: 'Hospital Furniture',
    slug: 'hospital-furniture',
    image: MEDICAL_IMAGES.categories.hospitalFurniture,
    description: 'Beds, exam tables, patient chairs',
    icon: '🛏️',
    productCount: PRODUCTS.filter(p => p.categorySlug === 'hospital-furniture').length,
  },
  {
    id: 4,
    name: 'Diagnostic',
    slug: 'diagnostic',
    image: MEDICAL_IMAGES.categories.diagnostic,
    description: 'BP monitors, stethoscopes, thermometers',
    icon: '🩺',
    productCount: PRODUCTS.filter(p => p.categorySlug === 'diagnostic').length,
  },
  {
    id: 5,
    name: 'PPE',
    slug: 'ppe',
    image: MEDICAL_IMAGES.categories.ppe,
    description: 'Masks, gloves, gowns, sanitizers',
    icon: '🧤',
    productCount: PRODUCTS.filter(p => p.categorySlug === 'ppe').length,
  },
  {
    id: 6,
    name: 'Home Care',
    slug: 'home-care',
    image: MEDICAL_IMAGES.categories.homeCare,
    description: 'Daily living aids and patient monitors',
    icon: '🏠',
    productCount: PRODUCTS.filter(p => p.categorySlug === 'home-care').length,
  },
];

// ============ TESTIMONIALS ============
export const TESTIMONIALS = [
  {
    id: 1,
    name: 'Dr. Joel M',
    role: 'Chief of Surgery',
    hospital: 'Kampala Hospital',
    image: MEDICAL_IMAGES.testimonials.doctor1,
    content: 'Goodwill Diagnostics Ltd has been our trusted partner for over 5 years. Their equipment quality and customer service are exceptional.',
    rating: 5,
  },
  {
    id: 2,
    name: 'Charlotte H',
    role: 'Home Care Patient',
    image: MEDICAL_IMAGES.testimonials.patient1,
    content: 'The home care equipment I purchased has greatly improved my quality of life. Professional service from start to finish.',
    rating: 5,
  },
  {
    id: 3,
    name: 'Dr. Sarah Chen',
    role: 'Medical Director',
    hospital: 'Platinum Medical Centre',
    image: MEDICAL_IMAGES.testimonials.doctor2,
    content: 'Reliable supplier with competitive pricing. Their diagnostic devices are top-notch and very accurate.',
    rating: 5,
  },
  {
    id: 4,
    name: 'James Wilson',
    role: 'Clinic Manager',
    hospital: 'Case Medical Care',
    image: MEDICAL_IMAGES.testimonials.patient2,
    content: 'Excellent customer support and fast delivery. We trust Goodwill Diagnostics for all our medical equipment needs.',
    rating: 5,
  },
];

// ============ BLOG POSTS ============
export const BLOG_POSTS = [
  {
    id: 1,
    title: 'The Future of Home Healthcare: Smart Medical Devices',
    slug: 'future-home-healthcare-smart-devices',
    excerpt: 'Discover how IoT-enabled medical devices are transforming patient care at home, improving outcomes, and reducing hospital readmissions.',
    content: '<p>Content here...</p>',
    author: 'Dr. Sarah Chen',
    authorRole: 'Chief Medical Officer',
    authorImage: MEDICAL_IMAGES.testimonials.doctor1,
    category: 'Healthcare Technology',
    tags: ['Smart Devices', 'IoT', 'Home Care'],
    image: MEDICAL_IMAGES.products.patientMonitor,
    date: '2024-01-15',
    readTime: 6,
    featured: true,
  },
  {
    id: 2,
    title: 'Understanding FDA Medical Device Classifications',
    slug: 'understanding-fda-medical-device-classifications',
    excerpt: 'A comprehensive guide to FDA device classifications and what they mean for healthcare providers and patients.',
    content: '<p>Content here...</p>',
    author: 'Michael Rodriguez',
    authorRole: 'Quality Assurance Director',
    authorImage: MEDICAL_IMAGES.testimonials.doctor2,
    category: 'Regulations',
    tags: ['FDA', 'Compliance', 'Safety'],
    image: MEDICAL_IMAGES.about.facility,
    date: '2024-01-10',
    readTime: 8,
    featured: true,
  },
  {
    id: 3,
    title: 'Essential PPE Guide for Healthcare Facilities',
    slug: 'essential-ppe-guide-healthcare-facilities',
    excerpt: 'Best practices for PPE selection, usage, and inventory management in hospitals and clinics.',
    content: '<p>Content here...</p>',
    author: 'Dr. Emily Watson',
    authorRole: 'Infection Control Specialist',
    authorImage: MEDICAL_IMAGES.testimonials.patient1,
    category: 'PPE',
    tags: ['PPE', 'Safety', 'Infection Control'],
    image: MEDICAL_IMAGES.categories.ppe,
    date: '2024-01-05',
    readTime: 5,
    featured: false,
  },
  {
    id: 4,
    title: 'Mobility Aids: Choosing the Right Equipment',
    slug: 'mobility-aids-choosing-right-equipment',
    excerpt: 'How to select the appropriate mobility aid for different patient needs and conditions.',
    content: '<p>Content here...</p>',
    author: 'James Park',
    authorRole: 'Physical Therapist',
    authorImage: MEDICAL_IMAGES.testimonials.patient2,
    category: 'Mobility',
    tags: ['Wheelchairs', 'Walkers', 'Patient Care'],
    image: MEDICAL_IMAGES.categories.mobility,
    date: '2023-12-28',
    readTime: 7,
    featured: false,
  },
  {
    id: 5,
    title: 'Respiratory Care: Advances in Oxygen Therapy',
    slug: 'respiratory-care-advances-oxygen-therapy',
    excerpt: 'New developments in portable oxygen concentrators and CPAP machines improving patient quality of life.',
    content: '<p>Content here...</p>',
    author: 'Dr. Sarah Chen',
    authorRole: 'Chief Medical Officer',
    authorImage: MEDICAL_IMAGES.testimonials.doctor1,
    category: 'Respiratory',
    tags: ['Oxygen', 'CPAP', 'Respiratory'],
    image: MEDICAL_IMAGES.categories.respiratory,
    date: '2023-12-20',
    readTime: 6,
    featured: false,
  },
  {
    id: 6,
    title: 'Hospital Bed Maintenance: Best Practices',
    slug: 'hospital-bed-maintenance-best-practices',
    excerpt: 'Extend the life of your hospital beds with proper maintenance and care protocols.',
    content: '<p>Content here...</p>',
    author: 'Michael Rodriguez',
    authorRole: 'Quality Assurance Director',
    authorImage: MEDICAL_IMAGES.testimonials.doctor2,
    category: 'Equipment Maintenance',
    tags: ['Hospital Beds', 'Maintenance'],
    image: MEDICAL_IMAGES.categories.hospitalFurniture,
    date: '2023-12-15',
    readTime: 5,
    featured: false,
  },
];
